### ISSUE TITLE
OAuthTokenResponse.ToToken fails on an invalid request

### ISSUE THREAD

**Issue by rich-jobadder** [cronofy/cronofy-csharp#1]
Hi there,

Have started using the API - and have a small blocker with the CronofyOAuthClient.GetTokenFromCode request. Have been trying to create a token from my code, and keep getting an NullReferenceException in the above call. 

After a bit of researching, I discovered the scope string was null and trying to convert it to the array was what was causing the Exception.

After struggling through trying to get a look on the what I was sending and receiving back from the request, I discovered I was getting a 400 bad request.

Anyway looking further, the ConcreteHttpClient gets the response (function line 138) - and happily processes it, and then the JSON deserialization happens and happily deserializes the response to an OAuthTokenResponse object, despite not containing any of the correct data.

So when ToToken() is called, none of the data is there and it causes a null reference exception.

Let me know if you require anymore information - it's 10:30PM here in Aus so I may not be completely fluent in my point :D

Thanks heaps
Richard Young
Senior Software Engineer
JobAdder

**Comment by gshutler** [comment]
Will get it sorted, thanks for the report.

**Comment by gshutler** [comment]
Version 0.0.4 means an exception will be raise in this case now.

For what it's worth, it looks like you were receiving a `400 Bad Request` as the `code` you were passing had already been used or had expired (they are short lived).

**Comment by rich-jobadder** [comment]
Excellent,

Thanks heaps for the fast turn around. Will let you know if I have any
problems with either issue.

Cheers
Richard
