### ISSUE TITLE
How to know what's new ?

### ISSUE THREAD

**Issue by ahmad-xlent** [cronofy/cronofy-csharp#17]
Hello is there anyway to know what is new in the new releases ?

**Comment by gshutler** [comment]
We tag all releases so they will show up on the [releases section](https://github.com/cronofy/cronofy-csharp/releases) and you can compare releases via diff like so https://github.com/cronofy/cronofy-csharp/compare/rel-0.1.1...rel-0.2.0

However, this raises a good point in that we should be maintaining a changelog to make this easier for people. I'll update our policy to include maintaining one going forward.

Thanks for the feedback.
