### ISSUE TITLE
Issue with [Content_Types].xml in nuget package

### ISSUE THREAD

**Issue by rich-jobadder** [cronofy/cronofy-csharp#2]
While I'm on a roll with issues, just wanted to flag this one as well. 

We use an internal nuget package repository that pipes through all packages on nuget.org

When I try to install the Cronofy package via our repository it fails (if I go via nuget.org it works ok). But I can't install any other packages because the Cronofy package was constantly blocking it (I would remove it from packages.config - do my updates, and then add it back in).

When it came time to package up the library that had the Cronofy package, it failed with the error

"'Default' tag requires a nonempty 'Extension' attribute. Position 1, Line 506

Google wasn't much help, apart from this random github issue : https://github.com/oxyplot/oxyplot/issues/184

So I downloaded the nuget package and went searching and found the issue in the above file:

```xml
<?xml version="1.0"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default ContentType="application/vnd.openxmlformats-package.relationships+xml" Extension="rels"/>
  <Default ContentType="application/octet" Extension="nuspec"/>
  <Default ContentType="application/octet" Extension="dll"/>
  <Default ContentType="application/octet" Extension="xml"/>
  <Default ContentType="application/octet" Extension="config"/>
  <Default ContentType="application/octet" Extension="csproj"/>
  <Default ContentType="application/octet" Extension="cs"/>
  <Default ContentType="application/octet" Extension=""/> <!-- Problem line -->
  <Default ContentType="application/octet" Extension="md"/>
  <Default ContentType="application/vnd.openxmlformats-package.core-properties+xml" Extension="psmdcp"/>
</Types>
```

Removing the offending line, and pushing it to our repository solved the problem completely.
Not 100% sure what would causing the issue, but did want to flag it.

Thanks heaps
Richard Young
Senior Software Engineer
JobAdder

**Comment by gshutler** [comment]
Hmm, that file is being generated by nuget.

I suspect its because a couple of files in the package have no extension (LICENSE and GITCOMMIT). I'll look into it and add an extension to those if needed.

**Comment by gshutler** [comment]
Version 0.0.4 no longer has an entry with an empty extension. Let us know if you have any further problems.
