### ISSUE TITLE
Event.Status property is wrongly named Event.EventStatus

### ISSUE THREAD

**Issue by miyconst** [cronofy/cronofy-csharp#63]
According to the specification and actual Cronofy behavior, the `Event.Status` property is called `status`, but the C# connector is expecting `event_status`, which is wrong.

- [Cronofy Docs - API Reference - Events - Read Events](https://docs.cronofy.com/developers/api/events/read-events/#events.status).
- [Cronofy.Responses.ReadEventsResponse.EventStatus](https://github.com/cronofy/cronofy-csharp/blob/dd0146087a3453f1f147e329447176d785cf7c80/src/Cronofy/Responses/ReadEventsResponse.cs#L174).

**Comment by gshutler** [comment]
This is fixed in [0.25.1](https://www.nuget.org/packages/Cronofy/0.25.1).
