### ISSUE TITLE
Typo in the application_calendars url

### ISSUE THREAD

**Issue by mahdibx** [cronofy/cronofy-csharp#67]
https://github.com/cronofy/cronofy-csharp/blob/1b4adc9cb2c7d3ae98308cd77c8f7569fedbe1dd/src/Cronofy/UrlProvider.cs#L131

the url referenced in the file is missing an "s" at the end.

**Comment by gshutler** [comment]
This was fixed in [0.25.2](https://www.nuget.org/packages/Cronofy/0.25.2), thanks for letting us know.
